const tagLabels: Record<string, string> = {
  "论文/科研资料": "Papers",
  "PDF/文档": "PDF / docs",
  "Office 文档": "Office docs",
  "网页/搜索结果": "Web / search",
  "新闻/资讯": "News",
  "代码库": "Codebase",
  "数据/表格": "Data / tables",
  "数据库": "Database",
  "知识库/个人资料": "Knowledge base",
  "文本/想法": "Text / ideas",
  "代码/技术描述": "Technical text",
  "DSL/代码": "DSL / code",
  "引用网络": "Citation graph",
  "任意/多源": "Multi-source",
  "产品/SaaS": "Product / SaaS",
  "开源应用/框架": "Open source",
  "Agent Skill": "Agent skill",
  "Skill 集合": "Skill collection",
  "MCP Server": "MCP server",
  "API/SDK/库": "API / SDK",
  "Bot/助手": "Bot / assistant",
  "研究原型": "Research",
  "数据集/评测": "Dataset",
  "Awesome/索引": "Awesome index",
  "PPT/演示文稿": "Deck",
  "报告/长文档": "Long report",
  "报告/简报": "Briefing",
  "网页/交互页面": "Interactive page",
  "图形摘要/信息图": "Graphical abstract",
  "信息图/视觉报告": "Visual report",
  "架构图/流程图": "Flow diagram",
  "白板/思维导图": "Whiteboard",
  "思维导图/知识地图": "Knowledge map",
  "文献地图/知识地图": "Literature map",
  "图表/仪表盘": "Dashboard",
  "表格/时间线": "Timeline",
  "代码地图/Repo Wiki": "Repo map",
  "图表/Mermaid": "Mermaid",
  "SVG/PNG/PDF": "SVG / PNG / PDF",
  "视频/音频": "Video / audio",
  "结构化数据/Markdown": "Structured data",
  "证据表": "Evidence table",
  "引用答案": "Cited answer",
  "问答/学习材料": "Study material",
  "工具索引": "Tool index",
  "图表/渲染输出": "Rendered chart",
  "浏览器/账号": "Browser account",
  "Agent 宿主": "Agent host",
  "模型 API": "Model API",
  "本地语言环境": "Local runtime",
  "系统工具": "System tools",
  "文档解析/OCR": "Parsing / OCR",
  "渲染/导出": "Rendering",
  "外部检索/数据源": "External data",
  "GPU/加速器": "GPU",
  "MCP Client": "MCP client",
  "代码分析工具": "Code analysis",
  "存储/索引": "Storage",
  "模板/素材": "Templates",
};

export const groupLabels: Record<string, string> = {
  paper: "Papers and research",
  web_news: "Web and intelligence",
  docs: "Documents and knowledge",
  code: "Codebase maps",
  data: "Data dashboards",
  text_visual: "Text and whiteboards",
  presentation: "Presentation tools",
  support_doc_parse: "Parsing support",
  support_render: "Rendering support",
  support_mindmap: "Mind-map support",
  indexes: "Discovery indexes",
};

export const categoryLabels: Record<string, string> = {
  "paper-visualization": "Paper visualization",
  "research-report": "Research reports",
  "literature-map": "Literature maps",
  "doc-to-knowledge": "Doc to knowledge",
  "infographic-report": "Infographics",
  "presentation-tools": "Presentation tools",
  "codebase-map": "Codebase maps",
  "diagram-generation": "Diagram generation",
  "data-dashboard": "Data dashboards",
  "commercial-site": "Commercial tools",
  "meta-index": "Meta indexes",
  "rendering-primitive": "Rendering primitives",
};

export const labelFor = (value: string) => tagLabels[value] ?? value;
